In [ ]:
import numpy as np
import pandas as pd
import scipy as sc
import os
from datetime import date
from os import listdir
from os.path import isfile, join
import math
from scipy.optimize import curve_fit

from operator import add

In [24]:
def threshup_():
    #DOI 10.1211/jpp.60.1.0008
    th_u_comft = 3.38 + 0.52
    #th_u_stretched = 4.63 + 0.44
    #th_u_burst = 6.63 + 0.92
    return th_u_comft


def real_consump(val, w, p):
    a = np.nan
    if (p == 5):
        a = (val*0.05*0.789)/(w) *1000
    elif (p == 10):
        a = (val*0.1*0.789)/(w) *1000
    elif ( p == 20 ):
        a = (val*0.2*0.789)/(w) *1000
    else:
        print("You messed up the input in real_consump function")
    return(a)

In [ ]:
file_ = df_w3.rename(columns={'Unnamed: 0': 'date', 'Unnamed: 1': 'time', 'Unnamed: 2': 'animal',
                                     'Unnamed: 3': 'box', '[ml]': 'water', '[ml].1': 'alcohol_5%',
                                     '[ml].2': 'alcohol_10%', '[ml].3': 'alcohol_20%'})
extracted_a1 = file_[file_['box'] == box]
list_index = list(file_[file_['box'] == box].index)
for i7 in range(len(extracted_a1)):
ind1 = main_df.loc[(main_df['date'] == extracted_a1['date'][list_index[i7]].strftime('%Y-%m-%d')) &
                    (main_df['time'] == extracted_a1['time'][list_index[i7]].strftime('%H:%M:%S'))].index[0]
main_df.loc[ind1, 'water'] = extracted_a1['water'][list_index[i7]]
main_df.loc[ind1, 'alcohol_5%'] = extracted_a1['alcohol_5%'][list_index[i7]]
main_df.loc[ind1, 'alcohol_10%'] = extracted_a1['alcohol_10%'][list_index[i7]]
main_df.loc[ind1, 'alcohol_20%'] = extracted_a1['alcohol_20%'][list_index[i7]]

In [46]:
path_ = os.getcwd()
path_ = path_+'\\data\\2021'
onlyfiles = [f for f in listdir("{}".format(path_))
             if isfile(join("{}".format(path_), f))]

In [49]:
onlyfiles[22]

'18_ADE5_30-06-21.xlsx'

In [50]:
df_w3 = pd.read_excel("{}\{}".format(path_, onlyfiles[26]), skiprows=35)
df_w2 = pd.read_excel("{}\{}".format(path_, onlyfiles[27]), skiprows=35)
df_w1 = pd.read_excel("{}\{}".format(path_, onlyfiles[28]), skiprows=35)
df_d12 = pd.read_excel("{}\{}".format(path_, onlyfiles[29]), skiprows=35)
df_x5  = pd.read_excel("{}\{}".format(path_, onlyfiles[22]), skiprows=35)

In [51]:
df_w3 = df_w3.rename(columns={'Unnamed: 0': 'date', 'Unnamed: 1': 'time', 'Unnamed: 2': 'animal',
                                     'Unnamed: 3': 'box', '[ml]': 'water', '[ml].1': 'alcohol_5%',
                                     '[ml].2': 'alcohol_10%', '[ml].3': 'alcohol_20%'})

df_w2 = df_w2.rename(columns={'Unnamed: 0': 'date', 'Unnamed: 1': 'time', 'Unnamed: 2': 'animal',
                                     'Unnamed: 3': 'box', '[ml]': 'water', '[ml].1': 'alcohol_5%',
                                     '[ml].2': 'alcohol_10%', '[ml].3': 'alcohol_20%'})

df_w1 = df_w1.rename(columns={'Unnamed: 0': 'date', 'Unnamed: 1': 'time', 'Unnamed: 2': 'animal',
                                     'Unnamed: 3': 'box', '[ml]': 'water', '[ml].1': 'alcohol_5%',
                                     '[ml].2': 'alcohol_10%', '[ml].3': 'alcohol_20%'})

df_d12 = df_d12.rename(columns={'Unnamed: 0': 'date', 'Unnamed: 1': 'time', 'Unnamed: 2': 'animal',
                                     'Unnamed: 3': 'box', '[ml]': 'water', '[ml].1': 'alcohol_5%',
                                     '[ml].2': 'alcohol_10%', '[ml].3': 'alcohol_20%'})

df_x5 = df_x5.rename(columns={'Unnamed: 0': 'date', 'Unnamed: 1': 'time', 'Unnamed: 2': 'animal',
                                     'Unnamed: 3': 'box', '[ml]': 'water', '[ml].1': 'alcohol_5%',
                                     '[ml].2': 'alcohol_10%', '[ml].3': 'alcohol_20%'})

In [52]:
for i in range(0,len(df_w1)-1,1):
    df_w1.loc[i, 'water'] = df_w1.loc[i+1, 'water'] - df_w1.loc[i, 'water']
    df_w1.loc[i, 'alcohol_5%'] = df_w1.loc[i+1, 'alcohol_5%'] - df_w1.loc[i, 'alcohol_5%']
    df_w1.loc[i, 'alcohol_10%'] = df_w1.loc[i+1, 'alcohol_10%'] - df_w1.loc[i, 'alcohol_10%']
    df_w1.loc[i, 'alcohol_20%'] = df_w1.loc[i+1, 'alcohol_20%'] - df_w1.loc[i, 'alcohol_20%']
    
for i in range(0,len(df_w2)-1,1):
    df_w2.loc[i, 'water'] = df_w2.loc[i+1, 'water'] - df_w2.loc[i, 'water']
    df_w2.loc[i, 'alcohol_5%'] = df_w2.loc[i+1, 'alcohol_5%'] - df_w2.loc[i, 'alcohol_5%']
    df_w2.loc[i, 'alcohol_10%'] = df_w2.loc[i+1, 'alcohol_10%'] - df_w2.loc[i, 'alcohol_10%']
    df_w2.loc[i, 'alcohol_20%'] = df_w2.loc[i+1, 'alcohol_20%'] - df_w2.loc[i, 'alcohol_20%']

for i in range(0,len(df_w3)-1,1):
    df_w3.loc[i, 'water'] = df_w2.loc[i+1, 'water'] - df_w3.loc[i, 'water']
    df_w3.loc[i, 'alcohol_5%'] = df_w3.loc[i+1, 'alcohol_5%'] - df_w3.loc[i, 'alcohol_5%']
    df_w3.loc[i, 'alcohol_10%'] = df_w3.loc[i+1, 'alcohol_10%'] - df_w3.loc[i, 'alcohol_10%']
    df_w3.loc[i, 'alcohol_20%'] = df_w3.loc[i+1, 'alcohol_20%'] - df_w3.loc[i, 'alcohol_20%']

for i in range(0,len(df_d12)-1,1):
    df_d12.loc[i, 'water'] = df_d12.loc[i+1, 'water'] - df_d12.loc[i, 'water']
    df_d12.loc[i, 'alcohol_5%'] = df_d12.loc[i+1, 'alcohol_5%'] - df_d12.loc[i, 'alcohol_5%']
    df_d12.loc[i, 'alcohol_10%'] = df_d12.loc[i+1, 'alcohol_10%'] - df_d12.loc[i, 'alcohol_10%']
    df_d12.loc[i, 'alcohol_20%'] = df_d12.loc[i+1, 'alcohol_20%'] - df_d12.loc[i, 'alcohol_20%']

for i in range(0,len(df_x5)-1,1):
    df_x5.loc[i, 'water'] = df_x5.loc[i+1, 'water'] - df_x5.loc[i, 'water']
    df_x5.loc[i, 'alcohol_5%'] = df_x5.loc[i+1, 'alcohol_5%'] - df_x5.loc[i, 'alcohol_5%']
    df_x5.loc[i, 'alcohol_10%'] = df_x5.loc[i+1, 'alcohol_10%'] - df_x5.loc[i, 'alcohol_10%']
    df_x5.loc[i, 'alcohol_20%'] = df_x5.loc[i+1, 'alcohol_20%'] - df_x5.loc[i, 'alcohol_20%']

In [53]:
df_w1.to_excel(r'{}\dataframes\drinkometer_df_w1.xlsx'.format(path_), index=False, header=True)
df_w2.to_excel(r'{}\dataframes\drinkometer_df_w2.xlsx'.format(path_), index=False, header=True)
df_w3.to_excel(r'{}\dataframes\drinkometer_df_w3.xlsx'.format(path_), index=False, header=True)
df_d12.to_excel(r'{}\dataframes\drinkometer_df_d12.xlsx'.format(path_), index=False, header=True)
df_x5.to_excel(r'{}\dataframes\drinkometer_df_x5.xlsx'.format(path_), index=False, header=True)

In [92]:
box = 6
dates_ = df_w2['date'].unique()
l = []
temp_ = df_w2.loc[(df_w2['date'] == df_w2['date'].unique()[0]) & (df_w2['box'] == subj)]['alcohol_10%'].values
temp__ = temp_[temp_ > 0.08]
l.append(np.nansum(temp__[temp__ < 3.38]))
temp_ = df_w2.loc[(df_w2['date'] == df_w2['date'].unique()[1]) & (df_w2['box'] == subj)]['alcohol_10%'].values
temp__ = temp_[temp_ > 0.08]
l.append(np.nansum(temp__[temp__ < 3.38]))
temp_ = df_w2.loc[(df_w2['date'] == df_w2['date'].unique()[2]) & (df_w2['box'] == subj)]['alcohol_10%'].values
temp__ = temp_[temp_ > 0.08]
l.append(np.nansum(temp__[temp__ < 3.38]))
temp_ = df_w2.loc[(df_w2['date'] == df_w2['date'].unique()[3]) & (df_w2['box'] == subj)]['alcohol_10%'].values
temp__ = temp_[temp_ > 0.08]
l.append(np.nansum(temp__[temp__ < 3.38]))
temp_ = df_w2.loc[(df_w2['date'] == df_w2['date'].unique()[4]) & (df_w2['box'] == subj)]['alcohol_10%'].values
temp__ = temp_[temp_ > 0.08]
l.append(np.nansum(temp__[temp__ < 3.38]))
temp_ = df_w2.loc[(df_w2['date'] == df_w2['date'].unique()[5]) & (df_w2['box'] == subj)]['alcohol_10%'].values
temp__ = temp_[temp_ > 0.08]
l.append(np.nansum(temp__[temp__ < 3.38]))
print(l)
real_l = []
for i in range(len(l)):
    real_l.append(real_consump(l[i], 450, 5))

[0.0, 1.5899999999999999, 3.6500000000000004, 2.79, 4.75, 1.75]

In [ ]:
print("Please enter the animal code:")
animal = int(input())
print("Please enter the box number:")
box = int(input())
print("Please enter the strain of the animal")
strain = input()
print("Please enter the gender of the animal")
gender = input()

In [164]:
df_m = pd.DataFrame(index=range(16), columns=['Subj', 'X1', 'X2', 'X3', 'X1_3_AVG', 
                                                               'w1', 'w2', 'w3', 'AVG', 'X5_ADE'])
df_f = pd.DataFrame(index=range(14), columns=['Subj', 'X1', 'X2', 'X3', 'X1_3_AVG', 
                                                               'w1', 'w2', 'w3', 'AVG', 'X5_ADE'])
subj_m = np.arange(17,33)
w_m = [491.7, 438.3, 486.1, 572, 475.2, 468.6, 446, 431.7, 452.9, 413,
      417.7, 491.1, 495.9, 500.3, 548.2, 524.7]

subj_f = np.array([1, 2, 3, 4, 5, 6, 8 , 9, 10, 11, 12 ,13, 14, 15])
w_f = [282.7, 340.6, 231.3, 301.9, 325.6, 328.7, 297.8, 295.2,
      306.7, 287.2, 276, 293.6, 301.9, 281.7]

df_m['Subj'] = subj_m
df_f['Subj'] = subj_f

In [133]:
x1 = []
x2 = []
x3 = []
x1_3_avg = 0
w1 = []
w2 = []
w3 = []
AVG = 0
x5_ade = []

In [165]:
temp_5 = []
temp_10 = []
temp_20 = []
for i in range(len(subj_m)):
    subj = subj_m[i]
    dates_ = df_w2['date'].unique()
    l = []
    temp_ = df_w2.loc[(df_w2['date'] == df_w2['date'].unique()[0]) & (df_w2['box'] == subj)]['alcohol_5%'].values
    temp__ = temp_[temp_ > 0.08]
    l.append(np.nansum(temp__[temp__ < 3.38]))
    temp_ = df_w2.loc[(df_w2['date'] == df_w2['date'].unique()[1]) & (df_w2['box'] == subj)]['alcohol_5%'].values
    temp__ = temp_[temp_ > 0.08]
    l.append(np.nansum(temp__[temp__ < 3.38]))
    temp_ = df_w2.loc[(df_w2['date'] == df_w2['date'].unique()[2]) & (df_w2['box'] == subj)]['alcohol_5%'].values
    temp__ = temp_[temp_ > 0.08]
    l.append(np.nansum(temp__[temp__ < 3.38]))
    temp_ = df_w2.loc[(df_w2['date'] == df_w2['date'].unique()[3]) & (df_w2['box'] == subj)]['alcohol_5%'].values
    temp__ = temp_[temp_ > 0.08]
    l.append(np.nansum(temp__[temp__ < 3.38]))
    temp_ = df_w2.loc[(df_w2['date'] == df_w2['date'].unique()[4]) & (df_w2['box'] == subj)]['alcohol_5%'].values
    temp__ = temp_[temp_ > 0.08]
    l.append(np.nansum(temp__[temp__ < 3.38]))
    temp_ = df_w2.loc[(df_w2['date'] == df_w2['date'].unique()[5]) & (df_w2['box'] == subj)]['alcohol_5%'].values
    temp__ = temp_[temp_ > 0.08]
    l.append(np.nansum(temp__[temp__ < 3.38]))
    #print(l)
    real_l = []
    for j in range(len(l)):
        real_l.append(real_consump(l[j], w_m[j], 5))
    temp_5.append(np.nanmean(real_l))
    
    
    l = []
    temp_ = df_w2.loc[(df_w2['date'] == df_w2['date'].unique()[0]) & (df_w2['box'] == subj)]['alcohol_10%'].values
    temp__ = temp_[temp_ > 0.08]
    l.append(np.nansum(temp__[temp__ < 3.38]))
    temp_ = df_w2.loc[(df_w2['date'] == df_w2['date'].unique()[1]) & (df_w2['box'] == subj)]['alcohol_10%'].values
    temp__ = temp_[temp_ > 0.08]
    l.append(np.nansum(temp__[temp__ < 3.38]))
    temp_ = df_w2.loc[(df_w2['date'] == df_w2['date'].unique()[2]) & (df_w2['box'] == subj)]['alcohol_10%'].values
    temp__ = temp_[temp_ > 0.08]
    l.append(np.nansum(temp__[temp__ < 3.38]))
    temp_ = df_w2.loc[(df_w2['date'] == df_w2['date'].unique()[3]) & (df_w2['box'] == subj)]['alcohol_10%'].values
    temp__ = temp_[temp_ > 0.08]
    l.append(np.nansum(temp__[temp__ < 3.38]))
    temp_ = df_w2.loc[(df_w2['date'] == df_w2['date'].unique()[4]) & (df_w2['box'] == subj)]['alcohol_10%'].values
    temp__ = temp_[temp_ > 0.08]
    l.append(np.nansum(temp__[temp__ < 3.38]))
    temp_ = df_w2.loc[(df_w2['date'] == df_w2['date'].unique()[5]) & (df_w2['box'] == subj)]['alcohol_10%'].values
    temp__ = temp_[temp_ > 0.08]
    l.append(np.nansum(temp__[temp__ < 3.38]))
    #print(l)
    real_l = []
    for j in range(len(l)):
        real_l.append(real_consump(l[j], w_m[j], 10))
    temp_10.append(np.nanmean(real_l))
    
    l = []
    temp_ = df_w2.loc[(df_w2['date'] == df_w2['date'].unique()[0]) & (df_w2['box'] == subj)]['alcohol_20%'].values
    temp__ = temp_[temp_ > 0.08]
    l.append(np.nansum(temp__[temp__ < 3.38]))
    temp_ = df_w2.loc[(df_w2['date'] == df_w2['date'].unique()[1]) & (df_w2['box'] == subj)]['alcohol_20%'].values
    temp__ = temp_[temp_ > 0.08]
    l.append(np.nansum(temp__[temp__ < 3.38]))
    temp_ = df_w2.loc[(df_w2['date'] == df_w2['date'].unique()[2]) & (df_w2['box'] == subj)]['alcohol_20%'].values
    temp__ = temp_[temp_ > 0.08]
    l.append(np.nansum(temp__[temp__ < 3.38]))
    temp_ = df_w2.loc[(df_w2['date'] == df_w2['date'].unique()[3]) & (df_w2['box'] == subj)]['alcohol_20%'].values
    temp__ = temp_[temp_ > 0.08]
    l.append(np.nansum(temp__[temp__ < 3.38]))
    temp_ = df_w2.loc[(df_w2['date'] == df_w2['date'].unique()[4]) & (df_w2['box'] == subj)]['alcohol_20%'].values
    temp__ = temp_[temp_ > 0.08]
    l.append(np.nansum(temp__[temp__ < 3.38]))
    temp_ = df_w2.loc[(df_w2['date'] == df_w2['date'].unique()[5]) & (df_w2['box'] == subj)]['alcohol_20%'].values
    temp__ = temp_[temp_ > 0.08]
    l.append(np.nansum(temp__[temp__ < 3.38]))
    #print(l)
    real_l = []
    for j in range(len(l)):
        real_l.append(real_consump(l[j], w_m[j], 20))
    temp_20.append(np.nanmean(real_l))

added_1 = list(map(add, temp_5, temp_10))
df_m['w2'] = list(map(add, added_1, temp_20))

In [166]:
temp_5 = []
temp_10 = []
temp_20 = []
for i in range(len(subj_f)):
    subj = subj_f[i]
    dates_ = df_w2['date'].unique()
    l = []
    temp_ = df_w2.loc[(df_w2['date'] == df_w2['date'].unique()[0]) & (df_w2['box'] == subj)]['alcohol_5%'].values
    temp__ = temp_[temp_ > 0.08]
    l.append(np.nansum(temp__[temp__ < 3.38]))
    temp_ = df_w2.loc[(df_w2['date'] == df_w2['date'].unique()[1]) & (df_w2['box'] == subj)]['alcohol_5%'].values
    temp__ = temp_[temp_ > 0.08]
    l.append(np.nansum(temp__[temp__ < 3.38]))
    temp_ = df_w2.loc[(df_w2['date'] == df_w2['date'].unique()[2]) & (df_w2['box'] == subj)]['alcohol_5%'].values
    temp__ = temp_[temp_ > 0.08]
    l.append(np.nansum(temp__[temp__ < 3.38]))
    temp_ = df_w2.loc[(df_w2['date'] == df_w2['date'].unique()[3]) & (df_w2['box'] == subj)]['alcohol_5%'].values
    temp__ = temp_[temp_ > 0.08]
    l.append(np.nansum(temp__[temp__ < 3.38]))
    temp_ = df_w2.loc[(df_w2['date'] == df_w2['date'].unique()[4]) & (df_w2['box'] == subj)]['alcohol_5%'].values
    temp__ = temp_[temp_ > 0.08]
    l.append(np.nansum(temp__[temp__ < 3.38]))
    temp_ = df_w2.loc[(df_w2['date'] == df_w2['date'].unique()[5]) & (df_w2['box'] == subj)]['alcohol_5%'].values
    temp__ = temp_[temp_ > 0.08]
    l.append(np.nansum(temp__[temp__ < 3.38]))
    #print(l)
    real_l = []
    for j in range(len(l)):
        real_l.append(real_consump(l[j], w_f[j], 5))
    temp_5.append(np.nanmean(real_l))
    
    
    l = []
    temp_ = df_w2.loc[(df_w2['date'] == df_w2['date'].unique()[0]) & (df_w2['box'] == subj)]['alcohol_10%'].values
    temp__ = temp_[temp_ > 0.08]
    l.append(np.nansum(temp__[temp__ < 3.38]))
    temp_ = df_w2.loc[(df_w2['date'] == df_w2['date'].unique()[1]) & (df_w2['box'] == subj)]['alcohol_10%'].values
    temp__ = temp_[temp_ > 0.08]
    l.append(np.nansum(temp__[temp__ < 3.38]))
    temp_ = df_w2.loc[(df_w2['date'] == df_w2['date'].unique()[2]) & (df_w2['box'] == subj)]['alcohol_10%'].values
    temp__ = temp_[temp_ > 0.08]
    l.append(np.nansum(temp__[temp__ < 3.38]))
    temp_ = df_w2.loc[(df_w2['date'] == df_w2['date'].unique()[3]) & (df_w2['box'] == subj)]['alcohol_10%'].values
    temp__ = temp_[temp_ > 0.08]
    l.append(np.nansum(temp__[temp__ < 3.38]))
    temp_ = df_w2.loc[(df_w2['date'] == df_w2['date'].unique()[4]) & (df_w2['box'] == subj)]['alcohol_10%'].values
    temp__ = temp_[temp_ > 0.08]
    l.append(np.nansum(temp__[temp__ < 3.38]))
    temp_ = df_w2.loc[(df_w2['date'] == df_w2['date'].unique()[5]) & (df_w2['box'] == subj)]['alcohol_10%'].values
    temp__ = temp_[temp_ > 0.08]
    l.append(np.nansum(temp__[temp__ < 3.38]))
    #print(l)
    real_l = []
    for j in range(len(l)):
        real_l.append(real_consump(l[j], w_f[j], 10))
    temp_10.append(np.nanmean(real_l))
    
    l = []
    temp_ = df_w2.loc[(df_w2['date'] == df_w2['date'].unique()[0]) & (df_w2['box'] == subj)]['alcohol_20%'].values
    temp__ = temp_[temp_ > 0.08]
    l.append(np.nansum(temp__[temp__ < 3.38]))
    temp_ = df_w2.loc[(df_w2['date'] == df_w2['date'].unique()[1]) & (df_w2['box'] == subj)]['alcohol_20%'].values
    temp__ = temp_[temp_ > 0.08]
    l.append(np.nansum(temp__[temp__ < 3.38]))
    temp_ = df_w2.loc[(df_w2['date'] == df_w2['date'].unique()[2]) & (df_w2['box'] == subj)]['alcohol_20%'].values
    temp__ = temp_[temp_ > 0.08]
    l.append(np.nansum(temp__[temp__ < 3.38]))
    temp_ = df_w2.loc[(df_w2['date'] == df_w2['date'].unique()[3]) & (df_w2['box'] == subj)]['alcohol_20%'].values
    temp__ = temp_[temp_ > 0.08]
    l.append(np.nansum(temp__[temp__ < 3.38]))
    temp_ = df_w2.loc[(df_w2['date'] == df_w2['date'].unique()[4]) & (df_w2['box'] == subj)]['alcohol_20%'].values
    temp__ = temp_[temp_ > 0.08]
    l.append(np.nansum(temp__[temp__ < 3.38]))
    temp_ = df_w2.loc[(df_w2['date'] == df_w2['date'].unique()[5]) & (df_w2['box'] == subj)]['alcohol_20%'].values
    temp__ = temp_[temp_ > 0.08]
    l.append(np.nansum(temp__[temp__ < 3.38]))
    #print(l)
    real_l = []
    for j in range(len(l)):
        real_l.append(real_consump(l[j], w_f[j], 20))
    temp_20.append(np.nanmean(real_l))

added_1 = list(map(add, temp_5, temp_10))
df_f['w2'] = list(map(add, added_1, temp_20))

In [167]:
temp_5 = []
temp_10 = []
temp_20 = []
for i in range(len(subj_m)):
    subj = subj_m[i]
    dates_ = df_w1['date'].unique()
    l = []
    temp_ = df_w1.loc[(df_w1['date'] == df_w1['date'].unique()[0]) & (df_w1['box'] == subj)]['alcohol_5%'].values
    temp__ = temp_[temp_ > 0.08]
    l.append(np.nansum(temp__[temp__ < 3.38]))
    temp_ = df_w1.loc[(df_w1['date'] == df_w1['date'].unique()[1]) & (df_w1['box'] == subj)]['alcohol_5%'].values
    temp__ = temp_[temp_ > 0.08]
    l.append(np.nansum(temp__[temp__ < 3.38]))
    temp_ = df_w1.loc[(df_w1['date'] == df_w1['date'].unique()[2]) & (df_w1['box'] == subj)]['alcohol_5%'].values
    temp__ = temp_[temp_ > 0.08]
    l.append(np.nansum(temp__[temp__ < 3.38]))
    temp_ = df_w1.loc[(df_w1['date'] == df_w1['date'].unique()[3]) & (df_w1['box'] == subj)]['alcohol_5%'].values
    temp__ = temp_[temp_ > 0.08]
    l.append(np.nansum(temp__[temp__ < 3.38]))
    temp_ = df_w1.loc[(df_w1['date'] == df_w1['date'].unique()[4]) & (df_w1['box'] == subj)]['alcohol_5%'].values
    temp__ = temp_[temp_ > 0.08]
    l.append(np.nansum(temp__[temp__ < 3.38]))
    temp_ = df_w1.loc[(df_w1['date'] == df_w1['date'].unique()[5]) & (df_w1['box'] == subj)]['alcohol_5%'].values
    temp__ = temp_[temp_ > 0.08]
    l.append(np.nansum(temp__[temp__ < 3.38]))
    #print(l)
    real_l = []
    for j in range(len(l)):
        real_l.append(real_consump(l[j], w_m[j], 5))
    temp_5.append(np.nanmean(real_l))
    
    
    l = []
    temp_ = df_w1.loc[(df_w1['date'] == df_w1['date'].unique()[0]) & (df_w1['box'] == subj)]['alcohol_10%'].values
    temp__ = temp_[temp_ > 0.08]
    l.append(np.nansum(temp__[temp__ < 3.38]))
    temp_ = df_w1.loc[(df_w1['date'] == df_w1['date'].unique()[1]) & (df_w1['box'] == subj)]['alcohol_10%'].values
    temp__ = temp_[temp_ > 0.08]
    l.append(np.nansum(temp__[temp__ < 3.38]))
    temp_ = df_w1.loc[(df_w1['date'] == df_w1['date'].unique()[2]) & (df_w1['box'] == subj)]['alcohol_10%'].values
    temp__ = temp_[temp_ > 0.08]
    l.append(np.nansum(temp__[temp__ < 3.38]))
    temp_ = df_w1.loc[(df_w1['date'] == df_w1['date'].unique()[3]) & (df_w1['box'] == subj)]['alcohol_10%'].values
    temp__ = temp_[temp_ > 0.08]
    l.append(np.nansum(temp__[temp__ < 3.38]))
    temp_ = df_w1.loc[(df_w1['date'] == df_w1['date'].unique()[4]) & (df_w1['box'] == subj)]['alcohol_10%'].values
    temp__ = temp_[temp_ > 0.08]
    l.append(np.nansum(temp__[temp__ < 3.38]))
    temp_ = df_w1.loc[(df_w1['date'] == df_w1['date'].unique()[5]) & (df_w1['box'] == subj)]['alcohol_10%'].values
    temp__ = temp_[temp_ > 0.08]
    l.append(np.nansum(temp__[temp__ < 3.38]))
    #print(l)
    real_l = []
    for j in range(len(l)):
        real_l.append(real_consump(l[j], w_m[j], 10))
    temp_10.append(np.nanmean(real_l))
    
    l = []
    temp_ = df_w1.loc[(df_w1['date'] == df_w1['date'].unique()[0]) & (df_w1['box'] == subj)]['alcohol_20%'].values
    temp__ = temp_[temp_ > 0.08]
    l.append(np.nansum(temp__[temp__ < 3.38]))
    temp_ = df_w1.loc[(df_w1['date'] == df_w1['date'].unique()[1]) & (df_w1['box'] == subj)]['alcohol_20%'].values
    temp__ = temp_[temp_ > 0.08]
    l.append(np.nansum(temp__[temp__ < 3.38]))
    temp_ = df_w1.loc[(df_w1['date'] == df_w1['date'].unique()[2]) & (df_w1['box'] == subj)]['alcohol_20%'].values
    temp__ = temp_[temp_ > 0.08]
    l.append(np.nansum(temp__[temp__ < 3.38]))
    temp_ = df_w1.loc[(df_w1['date'] == df_w1['date'].unique()[3]) & (df_w1['box'] == subj)]['alcohol_20%'].values
    temp__ = temp_[temp_ > 0.08]
    l.append(np.nansum(temp__[temp__ < 3.38]))
    temp_ = df_w1.loc[(df_w1['date'] == df_w1['date'].unique()[4]) & (df_w1['box'] == subj)]['alcohol_20%'].values
    temp__ = temp_[temp_ > 0.08]
    l.append(np.nansum(temp__[temp__ < 3.38]))
    temp_ = df_w1.loc[(df_w1['date'] == df_w1['date'].unique()[5]) & (df_w1['box'] == subj)]['alcohol_20%'].values
    temp__ = temp_[temp_ > 0.08]
    l.append(np.nansum(temp__[temp__ < 3.38]))
    #print(l)
    real_l = []
    for j in range(len(l)):
        real_l.append(real_consump(l[j], w_m[j], 20))
    temp_20.append(np.nanmean(real_l))

added_1 = list(map(add, temp_5, temp_10))
df_m['w1'] = list(map(add, added_1, temp_20))



temp_5 = []
temp_10 = []
temp_20 = []
for i in range(len(subj_f)):
    subj = subj_f[i]
    dates_ = df_w1['date'].unique()
    l = []
    temp_ = df_w1.loc[(df_w1['date'] == df_w1['date'].unique()[0]) & (df_w1['box'] == subj)]['alcohol_5%'].values
    temp__ = temp_[temp_ > 0.08]
    l.append(np.nansum(temp__[temp__ < 3.38]))
    temp_ = df_w1.loc[(df_w1['date'] == df_w1['date'].unique()[1]) & (df_w1['box'] == subj)]['alcohol_5%'].values
    temp__ = temp_[temp_ > 0.08]
    l.append(np.nansum(temp__[temp__ < 3.38]))
    temp_ = df_w1.loc[(df_w1['date'] == df_w1['date'].unique()[2]) & (df_w1['box'] == subj)]['alcohol_5%'].values
    temp__ = temp_[temp_ > 0.08]
    l.append(np.nansum(temp__[temp__ < 3.38]))
    temp_ = df_w1.loc[(df_w1['date'] == df_w1['date'].unique()[3]) & (df_w1['box'] == subj)]['alcohol_5%'].values
    temp__ = temp_[temp_ > 0.08]
    l.append(np.nansum(temp__[temp__ < 3.38]))
    temp_ = df_w1.loc[(df_w1['date'] == df_w1['date'].unique()[4]) & (df_w1['box'] == subj)]['alcohol_5%'].values
    temp__ = temp_[temp_ > 0.08]
    l.append(np.nansum(temp__[temp__ < 3.38]))
    temp_ = df_w1.loc[(df_w1['date'] == df_w1['date'].unique()[5]) & (df_w1['box'] == subj)]['alcohol_5%'].values
    temp__ = temp_[temp_ > 0.08]
    l.append(np.nansum(temp__[temp__ < 3.38]))
    #print(l)
    real_l = []
    for j in range(len(l)):
        real_l.append(real_consump(l[j], w_f[j], 5))
    temp_5.append(np.nanmean(real_l))
    
    
    l = []
    temp_ = df_w1.loc[(df_w1['date'] == df_w1['date'].unique()[0]) & (df_w1['box'] == subj)]['alcohol_10%'].values
    temp__ = temp_[temp_ > 0.08]
    l.append(np.nansum(temp__[temp__ < 3.38]))
    temp_ = df_w1.loc[(df_w1['date'] == df_w1['date'].unique()[1]) & (df_w1['box'] == subj)]['alcohol_10%'].values
    temp__ = temp_[temp_ > 0.08]
    l.append(np.nansum(temp__[temp__ < 3.38]))
    temp_ = df_w1.loc[(df_w1['date'] == df_w1['date'].unique()[2]) & (df_w1['box'] == subj)]['alcohol_10%'].values
    temp__ = temp_[temp_ > 0.08]
    l.append(np.nansum(temp__[temp__ < 3.38]))
    temp_ = df_w1.loc[(df_w1['date'] == df_w1['date'].unique()[3]) & (df_w1['box'] == subj)]['alcohol_10%'].values
    temp__ = temp_[temp_ > 0.08]
    l.append(np.nansum(temp__[temp__ < 3.38]))
    temp_ = df_w1.loc[(df_w1['date'] == df_w1['date'].unique()[4]) & (df_w1['box'] == subj)]['alcohol_10%'].values
    temp__ = temp_[temp_ > 0.08]
    l.append(np.nansum(temp__[temp__ < 3.38]))
    temp_ = df_w1.loc[(df_w1['date'] == df_w1['date'].unique()[5]) & (df_w1['box'] == subj)]['alcohol_10%'].values
    temp__ = temp_[temp_ > 0.08]
    l.append(np.nansum(temp__[temp__ < 3.38]))
    #print(l)
    real_l = []
    for j in range(len(l)):
        real_l.append(real_consump(l[j], w_f[j], 10))
    temp_10.append(np.nanmean(real_l))
    
    l = []
    temp_ = df_w1.loc[(df_w1['date'] == df_w1['date'].unique()[0]) & (df_w1['box'] == subj)]['alcohol_20%'].values
    temp__ = temp_[temp_ > 0.08]
    l.append(np.nansum(temp__[temp__ < 3.38]))
    temp_ = df_w1.loc[(df_w1['date'] == df_w1['date'].unique()[1]) & (df_w1['box'] == subj)]['alcohol_20%'].values
    temp__ = temp_[temp_ > 0.08]
    l.append(np.nansum(temp__[temp__ < 3.38]))
    temp_ = df_w1.loc[(df_w1['date'] == df_w1['date'].unique()[2]) & (df_w1['box'] == subj)]['alcohol_20%'].values
    temp__ = temp_[temp_ > 0.08]
    l.append(np.nansum(temp__[temp__ < 3.38]))
    temp_ = df_w1.loc[(df_w1['date'] == df_w1['date'].unique()[3]) & (df_w1['box'] == subj)]['alcohol_20%'].values
    temp__ = temp_[temp_ > 0.08]
    l.append(np.nansum(temp__[temp__ < 3.38]))
    temp_ = df_w1.loc[(df_w1['date'] == df_w1['date'].unique()[4]) & (df_w1['box'] == subj)]['alcohol_20%'].values
    temp__ = temp_[temp_ > 0.08]
    l.append(np.nansum(temp__[temp__ < 3.38]))
    temp_ = df_w1.loc[(df_w1['date'] == df_w1['date'].unique()[5]) & (df_w1['box'] == subj)]['alcohol_20%'].values
    temp__ = temp_[temp_ > 0.08]
    l.append(np.nansum(temp__[temp__ < 3.38]))
    #print(l)
    real_l = []
    for j in range(len(l)):
        real_l.append(real_consump(l[j], w_f[j], 20))
    temp_20.append(np.nanmean(real_l))

added_1 = list(map(add, temp_5, temp_10))
df_f['w1'] = list(map(add, added_1, temp_20))

In [168]:
temp_5 = []
temp_10 = []
temp_20 = []
for i in range(len(subj_m)):
    subj = subj_m[i]
    dates_ = df_w3['date'].unique()
    l = []
    temp_ = df_w3.loc[(df_w3['date'] == df_w3['date'].unique()[0]) & (df_w3['box'] == subj)]['alcohol_5%'].values
    temp__ = temp_[temp_ > 0.08]
    l.append(np.nansum(temp__[temp__ < 3.38]))
    temp_ = df_w3.loc[(df_w3['date'] == df_w3['date'].unique()[1]) & (df_w3['box'] == subj)]['alcohol_5%'].values
    temp__ = temp_[temp_ > 0.08]
    l.append(np.nansum(temp__[temp__ < 3.38]))
    temp_ = df_w3.loc[(df_w3['date'] == df_w3['date'].unique()[2]) & (df_w3['box'] == subj)]['alcohol_5%'].values
    temp__ = temp_[temp_ > 0.08]
    l.append(np.nansum(temp__[temp__ < 3.38]))
    temp_ = df_w3.loc[(df_w3['date'] == df_w3['date'].unique()[3]) & (df_w3['box'] == subj)]['alcohol_5%'].values
    temp__ = temp_[temp_ > 0.08]
    l.append(np.nansum(temp__[temp__ < 3.38]))
    temp_ = df_w3.loc[(df_w3['date'] == df_w3['date'].unique()[4]) & (df_w3['box'] == subj)]['alcohol_5%'].values
    temp__ = temp_[temp_ > 0.08]
    l.append(np.nansum(temp__[temp__ < 3.38]))
    temp_ = df_w3.loc[(df_w3['date'] == df_w3['date'].unique()[5]) & (df_w3['box'] == subj)]['alcohol_5%'].values
    temp__ = temp_[temp_ > 0.08]
    l.append(np.nansum(temp__[temp__ < 3.38]))
    #print(l)
    real_l = []
    for j in range(len(l)):
        real_l.append(real_consump(l[j], w_m[j], 5))
    temp_5.append(np.nanmean(real_l))
    
    
    l = []
    temp_ = df_w3.loc[(df_w3['date'] == df_w3['date'].unique()[0]) & (df_w3['box'] == subj)]['alcohol_10%'].values
    temp__ = temp_[temp_ > 0.08]
    l.append(np.nansum(temp__[temp__ < 3.38]))
    temp_ = df_w3.loc[(df_w3['date'] == df_w3['date'].unique()[1]) & (df_w3['box'] == subj)]['alcohol_10%'].values
    temp__ = temp_[temp_ > 0.08]
    l.append(np.nansum(temp__[temp__ < 3.38]))
    temp_ = df_w3.loc[(df_w3['date'] == df_w3['date'].unique()[2]) & (df_w3['box'] == subj)]['alcohol_10%'].values
    temp__ = temp_[temp_ > 0.08]
    l.append(np.nansum(temp__[temp__ < 3.38]))
    temp_ = df_w3.loc[(df_w3['date'] == df_w3['date'].unique()[3]) & (df_w3['box'] == subj)]['alcohol_10%'].values
    temp__ = temp_[temp_ > 0.08]
    l.append(np.nansum(temp__[temp__ < 3.38]))
    temp_ = df_w3.loc[(df_w3['date'] == df_w3['date'].unique()[4]) & (df_w3['box'] == subj)]['alcohol_10%'].values
    temp__ = temp_[temp_ > 0.08]
    l.append(np.nansum(temp__[temp__ < 3.38]))
    temp_ = df_w3.loc[(df_w3['date'] == df_w3['date'].unique()[5]) & (df_w3['box'] == subj)]['alcohol_10%'].values
    temp__ = temp_[temp_ > 0.08]
    l.append(np.nansum(temp__[temp__ < 3.38]))
    #print(l)
    real_l = []
    for j in range(len(l)):
        real_l.append(real_consump(l[j], w_m[j], 10))
    temp_10.append(np.nanmean(real_l))
    
    l = []
    temp_ = df_w3.loc[(df_w3['date'] == df_w3['date'].unique()[0]) & (df_w3['box'] == subj)]['alcohol_20%'].values
    temp__ = temp_[temp_ > 0.08]
    l.append(np.nansum(temp__[temp__ < 3.38]))
    temp_ = df_w3.loc[(df_w3['date'] == df_w3['date'].unique()[1]) & (df_w3['box'] == subj)]['alcohol_20%'].values
    temp__ = temp_[temp_ > 0.08]
    l.append(np.nansum(temp__[temp__ < 3.38]))
    temp_ = df_w3.loc[(df_w3['date'] == df_w3['date'].unique()[2]) & (df_w3['box'] == subj)]['alcohol_20%'].values
    temp__ = temp_[temp_ > 0.08]
    l.append(np.nansum(temp__[temp__ < 3.38]))
    temp_ = df_w3.loc[(df_w3['date'] == df_w3['date'].unique()[3]) & (df_w3['box'] == subj)]['alcohol_20%'].values
    temp__ = temp_[temp_ > 0.08]
    l.append(np.nansum(temp__[temp__ < 3.38]))
    temp_ = df_w3.loc[(df_w3['date'] == df_w3['date'].unique()[4]) & (df_w3['box'] == subj)]['alcohol_20%'].values
    temp__ = temp_[temp_ > 0.08]
    l.append(np.nansum(temp__[temp__ < 3.38]))
    temp_ = df_w3.loc[(df_w3['date'] == df_w3['date'].unique()[5]) & (df_w3['box'] == subj)]['alcohol_20%'].values
    temp__ = temp_[temp_ > 0.08]
    l.append(np.nansum(temp__[temp__ < 3.38]))
    #print(l)
    real_l = []
    for j in range(len(l)):
        real_l.append(real_consump(l[j], w_m[j], 20))
    temp_20.append(np.nanmean(real_l))

added_1 = list(map(add, temp_5, temp_10))
df_m['w3'] = list(map(add, added_1, temp_20))



temp_5 = []
temp_10 = []
temp_20 = []
for i in range(len(subj_f)):
    subj = subj_f[i]
    dates_ = df_w3['date'].unique()
    l = []
    temp_ = df_w3.loc[(df_w3['date'] == df_w3['date'].unique()[0]) & (df_w3['box'] == subj)]['alcohol_5%'].values
    temp__ = temp_[temp_ > 0.08]
    l.append(np.nansum(temp__[temp__ < 3.38]))
    temp_ = df_w3.loc[(df_w3['date'] == df_w3['date'].unique()[1]) & (df_w3['box'] == subj)]['alcohol_5%'].values
    temp__ = temp_[temp_ > 0.08]
    l.append(np.nansum(temp__[temp__ < 3.38]))
    temp_ = df_w3.loc[(df_w3['date'] == df_w3['date'].unique()[2]) & (df_w3['box'] == subj)]['alcohol_5%'].values
    temp__ = temp_[temp_ > 0.08]
    l.append(np.nansum(temp__[temp__ < 3.38]))
    temp_ = df_w3.loc[(df_w3['date'] == df_w3['date'].unique()[3]) & (df_w3['box'] == subj)]['alcohol_5%'].values
    temp__ = temp_[temp_ > 0.08]
    l.append(np.nansum(temp__[temp__ < 3.38]))
    temp_ = df_w3.loc[(df_w3['date'] == df_w3['date'].unique()[4]) & (df_w3['box'] == subj)]['alcohol_5%'].values
    temp__ = temp_[temp_ > 0.08]
    l.append(np.nansum(temp__[temp__ < 3.38]))
    temp_ = df_w3.loc[(df_w3['date'] == df_w3['date'].unique()[5]) & (df_w3['box'] == subj)]['alcohol_5%'].values
    temp__ = temp_[temp_ > 0.08]
    l.append(np.nansum(temp__[temp__ < 3.38]))
    #print(l)
    real_l = []
    for i in range(len(l)):
        real_l.append(real_consump(l[i], w_f[i], 5))
    temp_5.append(np.nanmean(real_l))
    
    
    l = []
    temp_ = df_w3.loc[(df_w3['date'] == df_w3['date'].unique()[0]) & (df_w3['box'] == subj)]['alcohol_10%'].values
    temp__ = temp_[temp_ > 0.08]
    l.append(np.nansum(temp__[temp__ < 3.38]))
    temp_ = df_w3.loc[(df_w3['date'] == df_w3['date'].unique()[1]) & (df_w3['box'] == subj)]['alcohol_10%'].values
    temp__ = temp_[temp_ > 0.08]
    l.append(np.nansum(temp__[temp__ < 3.38]))
    temp_ = df_w3.loc[(df_w3['date'] == df_w3['date'].unique()[2]) & (df_w3['box'] == subj)]['alcohol_10%'].values
    temp__ = temp_[temp_ > 0.08]
    l.append(np.nansum(temp__[temp__ < 3.38]))
    temp_ = df_w3.loc[(df_w3['date'] == df_w3['date'].unique()[3]) & (df_w3['box'] == subj)]['alcohol_10%'].values
    temp__ = temp_[temp_ > 0.08]
    l.append(np.nansum(temp__[temp__ < 3.38]))
    temp_ = df_w3.loc[(df_w3['date'] == df_w3['date'].unique()[4]) & (df_w3['box'] == subj)]['alcohol_10%'].values
    temp__ = temp_[temp_ > 0.08]
    l.append(np.nansum(temp__[temp__ < 3.38]))
    temp_ = df_w3.loc[(df_w3['date'] == df_w3['date'].unique()[5]) & (df_w3['box'] == subj)]['alcohol_10%'].values
    temp__ = temp_[temp_ > 0.08]
    l.append(np.nansum(temp__[temp__ < 3.38]))
    #print(l)
    real_l = []
    for i in range(len(l)):
        real_l.append(real_consump(l[i], w_f[i], 10))
    temp_10.append(np.nanmean(real_l))
    
    l = []
    temp_ = df_w3.loc[(df_w3['date'] == df_w3['date'].unique()[0]) & (df_w3['box'] == subj)]['alcohol_20%'].values
    temp__ = temp_[temp_ > 0.08]
    l.append(np.nansum(temp__[temp__ < 3.38]))
    temp_ = df_w3.loc[(df_w3['date'] == df_w3['date'].unique()[1]) & (df_w3['box'] == subj)]['alcohol_20%'].values
    temp__ = temp_[temp_ > 0.08]
    l.append(np.nansum(temp__[temp__ < 3.38]))
    temp_ = df_w3.loc[(df_w3['date'] == df_w3['date'].unique()[2]) & (df_w3['box'] == subj)]['alcohol_20%'].values
    temp__ = temp_[temp_ > 0.08]
    l.append(np.nansum(temp__[temp__ < 3.38]))
    temp_ = df_w3.loc[(df_w3['date'] == df_w3['date'].unique()[3]) & (df_w3['box'] == subj)]['alcohol_20%'].values
    temp__ = temp_[temp_ > 0.08]
    l.append(np.nansum(temp__[temp__ < 3.38]))
    temp_ = df_w3.loc[(df_w3['date'] == df_w3['date'].unique()[4]) & (df_w3['box'] == subj)]['alcohol_20%'].values
    temp__ = temp_[temp_ > 0.08]
    l.append(np.nansum(temp__[temp__ < 3.38]))
    temp_ = df_w3.loc[(df_w3['date'] == df_w3['date'].unique()[5]) & (df_w3['box'] == subj)]['alcohol_20%'].values
    temp__ = temp_[temp_ > 0.08]
    l.append(np.nansum(temp__[temp__ < 3.38]))
    #print(l)
    real_l = []
    for i in range(len(l)):
        real_l.append(real_consump(l[i], w_f, 20))
    temp_20.append(np.nanmean(real_l))

added_1 = list(map(add, temp_5, temp_10))
df_f['w3'] = list(map(add, added_1, temp_20))

In [169]:
temp_5_1 = []
temp_10_1 = []
temp_20_1 = []
temp_5_2 = []
temp_10_2 = []
temp_20_2 = []
temp_5_3 = []
temp_10_3 = []
temp_20_3 = []

for i in range(len(subj_m)):
    subj = subj_m[i]
    dates_ = df_d12['date'].unique()
    temp_ = df_d12.loc[(df_d12['date'] == df_d12['date'].unique()[0]) & (df_d12['box'] == subj)]['alcohol_5%'].values
    temp__ = temp_[temp_ > 0.08]
    l1 = np.nansum(temp__[temp__ < 3.38])
    temp_ = df_d12.loc[(df_d12['date'] == df_d12['date'].unique()[1]) & (df_d12['box'] == subj)]['alcohol_5%'].values
    temp__ = temp_[temp_ > 0.08]
    l2 = np.nansum(temp__[temp__ < 3.38])
    temp_ = df_d12.loc[(df_d12['date'] == df_d12['date'].unique()[2]) & (df_d12['box'] == subj)]['alcohol_5%'].values
    temp__ = temp_[temp_ > 0.08]
    l3 = np.nansum(temp__[temp__ < 3.38])
    #print(l2)
    temp_5_1.append(real_consump(l1, w_m[i], 5))
    temp_5_2.append(real_consump(l2, w_m[i], 5))
    temp_5_3.append(real_consump(l3, w_m[i], 5))
    
    
    
    dates_ = df_d12['date'].unique()
    temp_ = df_d12.loc[(df_d12['date'] == df_d12['date'].unique()[0]) & (df_d12['box'] == subj)]['alcohol_10%'].values
    temp__ = temp_[temp_ > 0.08]
    l1 = np.nansum(temp__[temp__ < 3.38])
    temp_ = df_d12.loc[(df_d12['date'] == df_d12['date'].unique()[1]) & (df_d12['box'] == subj)]['alcohol_10%'].values
    temp__ = temp_[temp_ > 0.08]
    l2 = np.nansum(temp__[temp__ < 3.38])
    temp_ = df_d12.loc[(df_d12['date'] == df_d12['date'].unique()[2]) & (df_d12['box'] == subj)]['alcohol_10%'].values
    temp__ = temp_[temp_ > 0.08]
    l3 = np.nansum(temp__[temp__ < 3.38])
    #print(l2)
    temp_10_1.append(real_consump(l1, w_m[i], 10))
    temp_10_2.append(real_consump(l2, w_m[i], 10))
    temp_10_3.append(real_consump(l3, w_m[i], 10))
    
    
    

    dates_ = df_d12['date'].unique()
    temp_ = df_d12.loc[(df_d12['date'] == df_d12['date'].unique()[0]) & (df_d12['box'] == subj)]['alcohol_20%'].values
    temp__ = temp_[temp_ > 0.08]
    l1 = np.nansum(temp__[temp__ < 3.38])
    temp_ = df_d12.loc[(df_d12['date'] == df_d12['date'].unique()[1]) & (df_d12['box'] == subj)]['alcohol_20%'].values
    temp__ = temp_[temp_ > 0.08]
    l2 = np.nansum(temp__[temp__ < 3.38])
    temp_ = df_d12.loc[(df_d12['date'] == df_d12['date'].unique()[2]) & (df_d12['box'] == subj)]['alcohol_20%'].values
    temp__ = temp_[temp_ > 0.08]
    l3 = np.nansum(temp__[temp__ < 3.38])
    #print(l2)
    temp_20_1.append(real_consump(l1, w_m[i], 20))
    temp_20_2.append(real_consump(l2, w_m[i], 20))
    temp_20_3.append(real_consump(l3, w_m[i], 20))

    
added_1 = []   
added_1 = list(map(add, temp_5_1, temp_10_1))
df_m['X1'] = list(map(add, added_1, temp_20_1))

added_1 = []   
added_1 = list(map(add, temp_5_2, temp_10_2))
df_m['X2'] = list(map(add, added_1, temp_20_2))

added_1 = []   
added_1 = list(map(add, temp_5_3, temp_10_3))
df_m['X3'] = list(map(add, added_1, temp_20_3))








temp_5_1 = []
temp_10_1 = []
temp_20_1 = []
temp_5_2 = []
temp_10_2 = []
temp_20_2 = []
temp_5_3 = []
temp_10_3 = []
temp_20_3 = []

for i in range(len(subj_f)):
    subj = subj_f[i]
    dates_ = df_d12['date'].unique()
    temp_ = df_d12.loc[(df_d12['date'] == df_d12['date'].unique()[0]) & (df_d12['box'] == subj)]['alcohol_5%'].values
    temp__ = temp_[temp_ > 0.08]
    l1 = np.nansum(temp__[temp__ < 3.38])
    temp_ = df_d12.loc[(df_d12['date'] == df_d12['date'].unique()[1]) & (df_d12['box'] == subj)]['alcohol_5%'].values
    temp__ = temp_[temp_ > 0.08]
    l2 = np.nansum(temp__[temp__ < 3.38])
    temp_ = df_d12.loc[(df_d12['date'] == df_d12['date'].unique()[2]) & (df_d12['box'] == subj)]['alcohol_5%'].values
    temp__ = temp_[temp_ > 0.08]
    l3 = np.nansum(temp__[temp__ < 3.38])
    #print(l2)
    temp_5_1.append(real_consump(l1, w_f[i], 5))
    temp_5_2.append(real_consump(l2, w_f[i], 5))
    temp_5_3.append(real_consump(l3, w_f[i], 5))
    
    
    

    dates_ = df_d12['date'].unique()
    temp_ = df_d12.loc[(df_d12['date'] == df_d12['date'].unique()[0]) & (df_d12['box'] == subj)]['alcohol_10%'].values
    temp__ = temp_[temp_ > 0.08]
    l1 = np.nansum(temp__[temp__ < 3.38])
    temp_ = df_d12.loc[(df_d12['date'] == df_d12['date'].unique()[1]) & (df_d12['box'] == subj)]['alcohol_10%'].values
    temp__ = temp_[temp_ > 0.08]
    l2 = np.nansum(temp__[temp__ < 3.38])
    temp_ = df_d12.loc[(df_d12['date'] == df_d12['date'].unique()[2]) & (df_d12['box'] == subj)]['alcohol_10%'].values
    temp__ = temp_[temp_ > 0.08]
    l3 = np.nansum(temp__[temp__ < 3.38])
    #print(l2)
    temp_10_1.append(real_consump(l1, w_f[i], 10))
    temp_10_2.append(real_consump(l2, w_f[i], 10))
    temp_10_3.append(real_consump(l3, w_f[i], 10))
    
    
    

    dates_ = df_d12['date'].unique()
    temp_ = df_d12.loc[(df_d12['date'] == df_d12['date'].unique()[0]) & (df_d12['box'] == subj)]['alcohol_20%'].values
    temp__ = temp_[temp_ > 0.08]
    l1 = np.nansum(temp__[temp__ < 3.38])
    temp_ = df_d12.loc[(df_d12['date'] == df_d12['date'].unique()[1]) & (df_d12['box'] == subj)]['alcohol_20%'].values
    temp__ = temp_[temp_ > 0.08]
    l2 = np.nansum(temp__[temp__ < 3.38])
    temp_ = df_d12.loc[(df_d12['date'] == df_d12['date'].unique()[2]) & (df_d12['box'] == subj)]['alcohol_20%'].values
    temp__ = temp_[temp_ > 0.08]
    l3 = np.nansum(temp__[temp__ < 3.38])
    #print(l2)
    temp_20_1.append(real_consump(l1, w_f[i], 20))
    temp_20_2.append(real_consump(l2, w_f[i], 20))
    temp_20_3.append(real_consump(l3, w_f[i], 20))

    
added_1 = []   
added_1 = list(map(add, temp_5_1, temp_10_1))
df_f['X1'] = list(map(add, added_1, temp_20_1))

added_1 = []   
added_1 = list(map(add, temp_5_2, temp_10_2))
df_f['X2'] = list(map(add, added_1, temp_20_2))

added_1 = []   
added_1 = list(map(add, temp_5_3, temp_10_3))
df_f['X3'] = list(map(add, added_1, temp_20_3))

In [170]:
df_m['X1_3_AVG'] = np.mean([df_m.X1.values, df_m.X2.values, df_m.X3.values], axis=0)
df_m['AVG'] = np.mean([df_m.w1.values, df_m.w2.values, df_m.w3.values], axis=0)

df_f['X1_3_AVG'] = np.mean([df_f.X1.values, df_f.X2.values, df_f.X3.values], axis=0)
df_f['AVG'] = np.mean([df_f.w1.values, df_f.w2.values, df_f.w3.values], axis=0)

In [171]:
temp_5_1 = []
temp_10_1 = []
temp_20_1 = []


for i in range(len(subj_m)):
    subj = subj_m[i]
    dates_ = df_x5['date'].unique()
    temp_ = df_x5.loc[(df_x5['date'] == df_x5['date'].unique()[0]) & (df_x5['box'] == subj)]['alcohol_5%'].values
    temp__ = temp_[temp_ > 0.08]
    l1 = np.nansum(temp__[temp__ < 3.38])
    #print(l2)
    temp_5_1.append(real_consump(l1, w_m[i], 5))

    
    
    
    subj = subj_m[i]
    dates_ = df_x5['date'].unique()
    temp_ = df_x5.loc[(df_x5['date'] == df_x5['date'].unique()[0]) & (df_x5['box'] == subj)]['alcohol_10%'].values
    temp__ = temp_[temp_ > 0.08]
    l1 = np.nansum(temp__[temp__ < 3.38])

    #print(l2)
    temp_10_1.append(real_consump(l1, w_m[i], 10))

    
    
    
    subj = subj_m[i]
    dates_ = df_x5['date'].unique()
    temp_ = df_x5.loc[(df_x5['date'] == df_x5['date'].unique()[0]) & (df_x5['box'] == subj)]['alcohol_20%'].values
    temp__ = temp_[temp_ > 0.08]
    l1 = np.nansum(temp__[temp__ < 3.38])

    #print(l2)
    temp_20_1.append(real_consump(l1, w_m[i], 20))


    
added_1 = []   
added_1 = list(map(add, temp_5_1, temp_10_1))
df_m['X5_ADE'] = list(map(add, added_1, temp_20_1))

In [172]:
temp_5_1 = []
temp_10_1 = []
temp_20_1 = []


for i in range(len(subj_f)):
    subj = subj_f[i]
    dates_ = df_x5['date'].unique()
    temp_ = df_x5.loc[(df_x5['date'] == df_x5['date'].unique()[0]) & (df_x5['box'] == subj)]['alcohol_5%'].values
    temp__ = temp_[temp_ > 0.08]
    l1 = np.nansum(temp__[temp__ < 3.38])
    #print(l2)
    temp_5_1.append(real_consump(l1, w_f[i], 5))

    
    
    
    subj = subj_m[i]
    dates_ = df_x5['date'].unique()
    temp_ = df_x5.loc[(df_x5['date'] == df_x5['date'].unique()[0]) & (df_x5['box'] == subj)]['alcohol_10%'].values
    temp__ = temp_[temp_ > 0.08]
    l1 = np.nansum(temp__[temp__ < 3.38])

    #print(l2)
    temp_10_1.append(real_consump(l1, w_f[i], 10))

    
    
    
    subj = subj_m[i]
    dates_ = df_x5['date'].unique()
    temp_ = df_x5.loc[(df_x5['date'] == df_x5['date'].unique()[0]) & (df_x5['box'] == subj)]['alcohol_20%'].values
    temp__ = temp_[temp_ > 0.08]
    l1 = np.nansum(temp__[temp__ < 3.38])

    #print(l2)
    temp_20_1.append(real_consump(l1, w_f[i], 20))


    
added_1 = []   
added_1 = list(map(add, temp_5_1, temp_10_1))
df_f['X5_ADE'] = list(map(add, added_1, temp_20_1))

In [174]:
df_f

,Subj,X1,X2,X3,X1_3_AVG,w1,w2,w3,AVG,X5_ADE
0,1,2.094604,5.209298,5.639103,4.314335,4.476697,4.830276,2.792300,4.033091,3.746843
1,2,2.506453,4.697863,3.905619,3.703312,4.522458,5.331750,3.738471,4.530893,2.382521
2,3,2.774974,5.913236,5.558476,4.748895,4.141334,2.783797,1.758755,2.894629,4.697160
3,4,2.017582,1.033619,1.494892,1.515364,0.755735,2.044786,2.112495,1.637672,4.495131
4,5,0.995943,2.471683,1.526628,1.664751,2.119746,2.305526,2.552155,2.325809,0.467681
5,6,2.349957,5.113978,4.281051,3.914995,5.294809,5.234962,3.022199,4.517324,2.855234
6,8,0.996185,1.568462,2.289107,1.617918,3.063851,3.070117,1.717658,2.617208,4.988875
7,9,1.670478,2.964096,3.783298,2.805957,2.372114,2.434616,2.774285,2.527005,3.655005
8,10,1.980861,1.686304,2.227825,1.964997,1.761904,2.152300,1.530691,1.814965,1.246399
9,11,3.315888,2.965618,2.471119,2.917542,2.732437,2.908445,4.660382,3.433754,0.543948
10,12,3.307511,5.097054,5.665935,4.690167,4.308886,3.940236,3.080657,3.776593,6.873734
11,13,2.484436,3.124021,4.471717,3.360058,4.856641,5.349372,4.183272,4.796428,3.093116
12,14,1.236161,3.253743,3.306012,2.598639,4.516488,4.814153,3.852041,4.394227,1.144690
13,15,1.865367,5.012125,5.402843,4.093445,5.604873,5.757930,3.606014,4.989606,3.038924

In [173]:
df_m

,Subj,X1,X2,X3,X1_3_AVG,w1,w2,w3,AVG,X5_ADE
0,17,0.875329,1.929576,2.576245,1.793717,1.389507,1.456269,1.011186,1.285654,2.050726
1,18,1.004476,2.806413,2.337478,2.049456,2.561559,2.354465,1.540989,2.152338,2.368980
2,19,1.392639,2.890782,2.940287,2.407903,1.938120,1.313579,1.086950,1.446216,1.658020
3,20,0.911764,1.951120,2.007674,1.623519,2.191085,1.682051,1.656582,1.843239,2.160784
4,21,0.998703,1.747522,2.213251,1.653159,1.414254,1.281169,1.113159,1.269527,1.691070
5,22,1.453067,3.014734,2.566860,2.344887,2.593445,2.584714,2.225392,2.467850,2.654414
6,23,1.127775,3.857432,3.659297,2.881501,2.177488,1.963559,1.522054,1.887700,2.929561
7,24,1.023489,2.507547,2.609896,2.046977,1.971721,1.909859,1.155235,1.678938,2.227915
8,25,0.807466,1.857085,2.421528,1.695360,1.874230,1.433712,1.135539,1.481160,0.000000
9,26,0.449902,3.022271,2.823588,2.098587,2.258259,1.874502,1.585947,1.906236,0.000000
10,27,1.433687,2.333755,4.278394,2.681945,2.235855,1.825658,1.292257,1.784590,3.026043
11,28,1.601778,2.760938,4.034166,2.798960,2.674936,2.305932,1.929379,2.303415,2.197022
12,29,1.165442,3.045263,2.542492,2.251066,3.068162,2.498443,2.219236,2.595281,0.000000
13,30,2.039131,3.982061,4.921985,3.647725,3.809090,2.829638,1.938968,2.859232,0.000000
14,31,1.226246,3.628364,2.921689,2.592100,2.730350,2.520417,2.568340,2.606369,0.000000
15,32,0.712762,1.602962,2.299182,1.538302,1.604870,1.431771,1.530745,1.522462,2.199937

In [175]:
df_m_final = df_m.rename(columns={'Subj': 'Subj', 'X1': '1', 'X2': '2',
                                     'X3': '3', 'X1_3_AVG': 'X1_3_AVG', 'w1': 'w1',
                                     'w2': 'w2', 'w3': 'w3' , 'AVG': 'AVG'
                                 , 'X5_ADE': '5_ADE'})

df_f_final = df_f.rename(columns={'Subj': 'Subj', 'X1': '1', 'X2': '2',
                                     'X3': '3', 'X1_3_AVG': 'X1_3_AVG', 'w1': 'w1',
                                     'w2': 'w2', 'w3': 'w3' , 'AVG': 'AVG'
                                 , 'X5_ADE': '5_ADE'})

In [176]:
df_m_final

,Subj,1,2,3,X1_3_AVG,w1,w2,w3,AVG,5_ADE
0,17,0.875329,1.929576,2.576245,1.793717,1.389507,1.456269,1.011186,1.285654,2.050726
1,18,1.004476,2.806413,2.337478,2.049456,2.561559,2.354465,1.540989,2.152338,2.368980
2,19,1.392639,2.890782,2.940287,2.407903,1.938120,1.313579,1.086950,1.446216,1.658020
3,20,0.911764,1.951120,2.007674,1.623519,2.191085,1.682051,1.656582,1.843239,2.160784
4,21,0.998703,1.747522,2.213251,1.653159,1.414254,1.281169,1.113159,1.269527,1.691070
5,22,1.453067,3.014734,2.566860,2.344887,2.593445,2.584714,2.225392,2.467850,2.654414
6,23,1.127775,3.857432,3.659297,2.881501,2.177488,1.963559,1.522054,1.887700,2.929561
7,24,1.023489,2.507547,2.609896,2.046977,1.971721,1.909859,1.155235,1.678938,2.227915
8,25,0.807466,1.857085,2.421528,1.695360,1.874230,1.433712,1.135539,1.481160,0.000000
9,26,0.449902,3.022271,2.823588,2.098587,2.258259,1.874502,1.585947,1.906236,0.000000
10,27,1.433687,2.333755,4.278394,2.681945,2.235855,1.825658,1.292257,1.784590,3.026043
11,28,1.601778,2.760938,4.034166,2.798960,2.674936,2.305932,1.929379,2.303415,2.197022
12,29,1.165442,3.045263,2.542492,2.251066,3.068162,2.498443,2.219236,2.595281,0.000000
13,30,2.039131,3.982061,4.921985,3.647725,3.809090,2.829638,1.938968,2.859232,0.000000
14,31,1.226246,3.628364,2.921689,2.592100,2.730350,2.520417,2.568340,2.606369,0.000000
15,32,0.712762,1.602962,2.299182,1.538302,1.604870,1.431771,1.530745,1.522462,2.199937

In [177]:
df_m_final.to_csv(r'{}\dataframes\baseline_m.csv'.format(path_), index=False, header=True)
df_f_final.to_csv(r'{}\dataframes\baseline_f.csv'.format(path_), index=False, header=True)